from enum import StrEnum


class ConversationState(StrEnum):
    START = "START"
    ASK_PRIVACY_CONSENT = "ASK_PRIVACY_CONSENT"
    ASK_PRODUCT = "ASK_PRODUCT"
    ASK_NATIONAL_ID = "ASK_NATIONAL_ID"
    ASK_BUREAU_CONSENT = "ASK_BUREAU_CONSENT"
    ASK_NAME = "ASK_NAME"
    ASK_AGE = "ASK_AGE"
    ASK_EMPLOYMENT = "ASK_EMPLOYMENT"
    ASK_EMPLOYMENT_TENURE = "ASK_EMPLOYMENT_TENURE"
    ASK_AMOUNT = "ASK_AMOUNT"
    ASK_TERM = "ASK_TERM"
    ASK_INCOME = "ASK_INCOME"
    ASK_EXPENSES = "ASK_EXPENSES"
    ASK_DEBTS = "ASK_DEBTS"
    ASK_PEP_STATUS = "ASK_PEP_STATUS"
    SHOW_RESULT = "SHOW_RESULT"
    HANDOFF = "HANDOFF"
    END = "END"
